import json
import os
import pathlib

os.environ["AUTH_DISABLED"] = "1"

from fastapi.testclient import TestClient

from app import kb, quote, rules
from app.main import app

c = TestClient(app)
COROLLA = {"name": "Toyota Corolla 2018", "kind": "ice"}
LEAF = {"name": "Nissan Leaf 2020 (EV)", "kind": "ev"}


def start(text, vehicle=COROLLA, **extra):
    return c.post("/requests", json={"text": text, "vehicle": vehicle, "history": [], **extra}).json()


def test_matches_typescript_pipeline_on_reference_cases():
    """tests/ts_reference.json was generated by running the real lib/pipeline.ts."""
    cases = json.loads((pathlib.Path(__file__).parent / "ts_reference.json").read_text())
    for case in cases:
        t = kb.norm(case["text"])
        hits = [{"id": e.id, "title": e.title, "doc": e.doc, "risk": e.risk} for e in kb.match(t)]
        r = rules.assess_risk(hits, [], None, case["kind"], t)
        ref = case["out"]
        assert (r.level, r.confidence, r.escalate, r.reason, [h["id"] for h in hits]) == (
            ref["risk"], ref["confidence"], ref["escalate"], ref["reason"], ref["hits"]), case["text"]
        if hits:
            q = quote.quote_for_hits([h["id"] for h in hits], None)
            q.pop("range", None)
            ref_q = dict(ref["quote"])
            assert abs(q.pop("hours") - ref_q.pop("hours")) < 1e-9
            assert q == ref_q, case["text"]


def test_word_boundary_bug_stays_fixed():
    assert "ac" not in [e.id for e in kb.match(kb.norm("noise from the back of the car"))]
    assert "ac" in [e.id for e in kb.match(kb.norm("AC not cold"))]


def test_brake_squeal_asks_questions_then_escalates_with_inspection_first_range():
    r = start("Brakes squeal when stopping")
    assert r["status"] == "needs_clarification" and len(r["awaiting"]["questions"]) == 3
    rid = r["request_id"]
    r = c.post(f"/requests/{rid}/clarify", json={"answers": {"sound": "squeal", "pedal": "normal", "warning": "no"}}).json()
    assert r["status"] == "pending_technician"
    assert r["risk"]["level"] == "high" and r["risk"]["escalate"] and r["risk"]["reason"] == "Safety-critical topic"
    assert r["quote"]["totalCents"] == 28652                       # full scope = existing demo total
    assert r["quote"]["range"] == {"lowCents": 10672, "highCents": 28652, "lowLabel": "Pads only",
                                   "highLabel": "Pads and rotors", "note": "Final scope is confirmed by a technician after inspection."}
    assert r["retrieval"][0]["source"] == "Brake Service Manual 4.2"
    assert r["hits"][0]["id"] == "brakes" and r["text"] == "Brakes squeal when stopping"


def test_grinding_answer_advises_not_driving():
    rid = start("Brakes squeal when stopping")["request_id"]
    r = c.post(f"/requests/{rid}/clarify", json={"answers": {"sound": "grinding", "pedal": "normal", "warning": "no"}}).json()
    assert r["recommendation"]["advise_not_to_drive"] is True


def test_technician_more_info_then_approve_loops_and_trace_is_complete():
    rid = start("Brakes grinding and warning light on")["request_id"]
    assert c.get(f"/requests/{rid}").json()["status"] == "pending_technician"
    r = c.post(f"/requests/{rid}/resume", json={"action": "more_info", "note": "Which wheel?"}).json()
    assert r["status"] == "pending_technician"                      # still open
    r = c.post(f"/requests/{rid}/resume", json={"action": "approve", "note": "Book inspection"}).json()
    assert r["status"] == "approved"
    names = [t["name"] for t in r["trace"]]
    assert names == ["Request Parser", "Vehicle Context", "Risk Assessment", "Knowledge Retrieval", "Agent Decision",
                     "Controlled Tool Execution", "Recommendation Builder", "Technician Review", "Technician Review"]
    assert c.post(f"/requests/{rid}/resume", json={"action": "approve"}).status_code == 409   # closed now


def test_routine_request_does_not_escalate():
    r = start("Oil change please")
    assert r["status"] == "ready_to_book" and not r["risk"]["escalate"] and r["risk"]["reason"] == ""


def test_unknown_noise_escalates_and_still_gets_a_diagnostic_quote():
    r = start("Strange noise, not sure what")
    assert r["status"] == "pending_technician" and r["risk"]["reason"] == "Low confidence match" and r["risk"]["confidence"] == 20
    assert r["quote"]["totalCents"] > 0 and r["quote"]["parts"] == []


def test_ev_battery_work_escalates_as_high_voltage_but_petrol_does_not():
    ev = start("Battery keeps dying", LEAF)
    assert ev["status"] == "pending_technician" and ev["risk"]["reason"] == "High-voltage EV system"
    assert start("Battery keeps dying", COROLLA)["status"] == "ready_to_book"


def test_live_prices_and_history_from_the_web_app_are_used():
    prices = {"OIL-5L": {"name": "Engine oil 5L", "cents": 10000}, "OIL-FLT": {"name": "Oil filter", "cents": 1000}}
    r = c.post("/requests", json={"text": "Oil change please", "vehicle": COROLLA, "history": ["a", "b"], "prices": prices}).json()
    assert r["quote"]["partsCents"] == 11000 and len(r["quote"]["parts"]) == 2
    assert r["trace"][1]["detail"] == "Toyota Corolla 2018; 2 service history records loaded"


def test_customer_cannot_use_technician_endpoint_or_see_others():
    rid = c.post("/requests", json={"text": "Brakes grinding", "vehicle": COROLLA, "history": []}, headers={"X-Dev-Role": "technician"}).json()["request_id"]
    assert c.post(f"/requests/{rid}/resume", json={"action": "approve"}, headers={"X-Dev-Role": "customer"}).status_code == 403
    assert c.get(f"/requests/{rid}", headers={"X-Dev-Role": "customer"}).status_code == 403


def test_resume_before_escalation_is_rejected():
    rid = start("Oil change please")["request_id"]
    assert c.post(f"/requests/{rid}/resume", json={"action": "approve"}).status_code == 409


def test_service_token_auth(monkeypatch):
    import time

    import jwt

    from app import config
    monkeypatch.setattr(config, "AUTH_DISABLED", False)
    monkeypatch.setattr(config, "AGENT_SERVICE_SECRET", "s" * 40)
    body = {"text": "Oil change please", "vehicle": {"name": "Honda Civic 2016"}, "history": []}

    def tok(role, secret="s" * 40, exp=120, sub="7"):
        return {"Authorization": "Bearer " + jwt.encode({"sub": sub, "role": role, "exp": int(time.time()) + exp}, secret, algorithm="HS256")}

    assert c.post("/requests", json=body).status_code == 401
    assert c.post("/requests", json=body, headers=tok("customer", secret="x" * 40)).status_code == 401
    assert c.post("/requests", json=body, headers=tok("customer", exp=-5)).status_code == 401
    assert c.post("/requests", json=body, headers=tok("admin")).status_code == 403
    ok = c.post("/requests", json=body, headers=tok("customer"))
    assert ok.status_code == 200
    rid = ok.json()["request_id"]
    assert c.get(f"/requests/{rid}", headers=tok("customer", sub="8")).status_code == 403
    assert c.get(f"/requests/{rid}", headers=tok("customer")).status_code == 200
    assert c.get(f"/requests/{rid}", headers=tok("technician", sub="1")).status_code == 200
